### ISSUE TITLE
Are you still working on it?

### ISSUE THREAD

**Issue by shun9092** [SlowpokeVG/Dragon-Engine-armp-converter#1]
Are you still working on it?

**Comment by SlowpokeVG** [comment]
No. 
https://github.com/CapitanRetraso/reARMP This project is in active development tho

**Comment by shun9092** [comment]
Thank you.

**Comment by shun9092** [comment]
Is this file available for analysis?

This is file 'cmn.bin'.
This file is used by Yakuza 6. Is this file possible?

https://drive.google.com/file/d/1Z0zfthZ3VAyYYMg6nzUjEh3hh7g-tCls/view?usp=sharing
https://drive.google.com/file/d/1gsgq5_QRMJZWlpq0-ALgAr7xpeKilxnV/view?usp=sharing
https://drive.google.com/file/d/1SP3XB0Y6r7-h_f9LWVSdmWSKiBDXvs1P/view?usp=sharing
https://drive.google.com/file/d/1MLsb08q6Xzaiuccr-JwOh8FmD4YM2UE7/view?usp=sharing
https://drive.google.com/file/d/1n31gFZjFmRZMpK0lYQkU-TQ_gUz9DfeC/view?usp=sharing

If possible, I'd like to modify it.
It is JPN file.
